/*
 * Custom fonts: struct-copy built-in Montserrat and chain a tiny fallback
 * that covers µ (U+00B5), ² (U+00B2), ³ (U+00B3), ° (U+00B0).
 *
 * Zero glyph-data duplication — only the small descriptor struct is copied.
 * SPDX-License-Identifier: MIT
 */

#include "app/fonts/app_fonts.h"

/* Tiny fallback fonts generated by lv_font_conv (Montserrat-Medium, bpp 4). */
extern const lv_font_t font_unit_14;
extern const lv_font_t font_unit_32;

/* Chinese fonts (Noto Sans SC, ~53 glyphs subset). */
extern const lv_font_t font_cn_14;
extern const lv_font_t font_cn_20;

lv_font_t app_font_14;
lv_font_t app_font_20;
lv_font_t app_font_32;
lv_font_t app_font_cn_14;
lv_font_t app_font_cn_20;

void app_fonts_init(void)
{
    /* Struct copy — pointers to const glyph data remain valid. */
    app_font_14 = lv_font_montserrat_14;
    app_font_14.fallback = &font_unit_14;

    app_font_20 = lv_font_montserrat_20;
    app_font_20.fallback = &font_unit_14; /* 14 px fallback is close enough for 20 px */

    app_font_32 = lv_font_montserrat_32;
    app_font_32.fallback = &font_unit_32;

    /* Chinese fonts: Noto Sans SC (CN glyphs) + Montserrat (ASCII + °µ²³)
     * merged in one font file — no fallback needed for mixed CN+EN text. */
    app_font_cn_14 = font_cn_14;
    app_font_cn_20 = font_cn_20;
}
